### ISSUE TITLE
富文本编辑全屏只显示了遮罩层！第一次提Issue，望尽快解决哦

### ISSUE THREAD

**Issue by ncc0706** [Wizzercn/NodeWk#2]

**Comment by Wizzercn** [comment]
百度编辑器和模态框不兼容的问题：
https://github.com/fex-team/ueditor/issues/1173

通过教程修改后依旧不能解决，暂时可在微信模块编辑器配置文件ueditor.configWx.js里把全屏按钮屏蔽。。

**Comment by mengkeys** [comment]
我这边已经解决了 https://github.com/fex-team/ueditor/issues/1173
