### ISSUE TITLE
一些BUG反馈

### ISSUE THREAD

**Issue by eddiechowx** [Wizzercn/NodeWk#5]
浏览器：Firefox 48.0.2  Chrome 50.0.2661.102 m
操作系统：win10
发现的一些问题
1、首页显示
Firefox下首页空白 chrome能正常显示 版本信息、捐赠清单等
2、角色管理
新建角色的时候，Firefox不能正常展示表单，chrome可以，但chrome在第二步的时候无法加载菜单树，一直loading
截图反馈如下
![qq 20160831153814](https://cloud.githubusercontent.com/assets/11539740/18120247/397800c4-6f91-11e6-94e1-fd3484639fad.png)
![qq 20160831153852](https://cloud.githubusercontent.com/assets/11539740/18120248/39823418-6f91-11e6-842a-ebcae62476b4.png)
![qq 20160831153943](https://cloud.githubusercontent.com/assets/11539740/18120249/39a7089c-6f91-11e6-9557-0820f0916db0.png)

**Comment by Wizzercn** [comment]
你截图是NutzWk 的演示地址，而不是你本地部署的测试结果，演示地址一般不会是最新代码，不做回复。

**Comment by eddiechowx** [comment]
哦，我以为演示地址是做了同步更新的，那我down到本地后再看下
