### ISSUE TITLE
运行不了。

### ISSUE THREAD

**Issue by tapqr** [Wizzercn/NodeWk#6]
`Error occurred in session middleware :: 'ReplyError: ERR unknown command \'get\'\n at new Command (E:\\source\\workspace\\NodeWk-master\\node_modules\\redis\\lib\\command.js:12:22)\n at RedisClient.get (E:\\source\\workspace\\NodeWk-master\\node_modules\\redis\\lib\\commands.js:62:47)\n at RedisStore.get (E:\\source\\workspace\\NodeWk-master\\node_modules\\connect-redis\\lib\\connect-redis.js:146:18)\n at session (E:\\source\\workspace\\NodeWk-master\\node_modules\\express-session\\index.js:444:11)\n at Object._.defaults.session [as handle] (E:\\source\\workspace\\NodeWk-master\\node_modules\\sails\\lib\\hooks\\http\\get-configured-http-middleware-fns.js:102:11)\n at next (E:\\source\\workspace\\NodeWk-master\\node_modules\\express\\node_modules\\connect\\lib\\proto.js:174:15)\n at Object.cookieParser [as handle] (E:\\source\\workspace\\NodeWk-master\\node_modules\\sails\\node_modules\\cookie-parser\\index.js:48:5)\n at next (E:\\source\\workspace\\NodeWk-master\\node_modules\\express\\node_modules\\connect\\lib\\proto.js:174:15)\n at Object.startRequestTimer [as handle] (E:\\source\\workspace\\NodeWk-master\\node_modules\\sails\\lib\\hooks\\http\\get-configured-http-middleware-fns.js:134:7)\n at next (E:\\source\\workspace\\NodeWk-master\\node_modules\\express\\node_modules\\connect\\lib\\proto.js:174:15)\n at Object._exposeSailsOnReq [as handle] (E:\\source\\workspace\\NodeWk-master\\node_modules\\sails\\lib\\hooks\\http\\initialize.js:198:16)\n at next (E:\\source\\workspace\\NodeWk-master\\node_modules\\express\\node_modules\\connect\\lib\\proto.js:174:15)\n at Object.expressInit [as handle] (E:\\source\\workspace\\NodeWk-master\\node_modules\\express\\lib\\middleware.js:30:5)\n at next (E:\\source\\workspace\\NodeWk-master\\node_modules\\express\\node_modules\\connect\\lib\\proto.js:174:15)\n at Object.query [as handle] (E:\\source\\workspace\\NodeWk-master\\node_modules\\express\\node_modules\\connect\\lib\\middleware\\query.js:43:5)\n at next (E:\\source\\workspace\\NodeWk-master\\node_modules\\express\\node_modules\\connect\\lib\\proto.js:174:15)\n at Function.app.handle (E:\\source\\workspace\\NodeWk-master\\node_modules\\express\\node_modules\\connect\\lib\\proto.js:182:3)\n at Server.app (E:\\source\\workspace\\NodeWk-master\\node_modules\\express\\node_modules\\connect\\lib\\connect.js:67:37)\n at Server. (E:\\source\\workspace\\NodeWk-master\\node_modules\\sails-hook-sockets\\node_modules\\engine.io\\lib\\server.js:443:22)\n at emitTwo (events.js:106:13)\n at Server.emit (events.js:191:7)\n at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:547:12)'`
![qq 20161205154846](https://cloud.githubusercontent.com/assets/7704110/20877271/7e038b52-bb02-11e6-9977-797a598f4484.png)

**Comment by Wizzercn** [comment]
请仔细阅读项目首页 readme 。

**Comment by tapqr** [comment]
难道不能在window环境下运行？

已经按照README操作,
node 版本6.5,0，7.1.0 都尝试过
mysql 版本：5.7.16
运行环境：window10

先执行npm install 然后 npm start
执行到grunt的watch任务之前不报错，访问127.0.0.1的时候报错。

**Comment by Wizzercn** [comment]
稍等 我来试试

**Comment by Wizzercn** [comment]
node 7 正常启动，没问题啊？

NodeWk\config\custom\mysql.js
NodeWk\config\custom\redis.js

请检查两个文件配的可对。
启动命令是> node app.js

**Comment by compasss** [comment]
是不是有些依耐包没有保存到package里面？
