### ISSUE TITLE
求大神帮我看看，检查了好多遍...连接数据库一直失败...

### ISSUE THREAD

**Issue by AldesFhh** [Wizzercn/NodeWk#7]
Redis 没问题，
```
/**
 *  auth_pass Redis连接密码
 * Created by root on 9/17/15.
 */
module.exports.redis = {
  host: '127.0.0.1',
  port: 6379,
  auth_pass: ''
};
```

mysql连接就有问题了
```
module.exports.mysql = {
  host: 'localhost',
  user: 'root',
  password: '',
  database: 'nw',
  pool: true,
  connectionLimit: 50,
  waitForConnections: true
};
```
自己新建的sails.js连接数据库没问题...
![image](https://cloud.githubusercontent.com/assets/17841236/26325442/72691050-3f69-11e7-9d1d-4334325d080d.png)

![image](https://cloud.githubusercontent.com/assets/17841236/26325464/912bdc66-3f69-11e7-9470-8528a6f8ff9d.png)

**Comment by Wizzercn** [comment]
执行下 nodewk.sql

**Comment by AldesFhh** [comment]
执行完了，数据库nw有数据，也是报这个错....

**Comment by lanhaoxiang** [comment]
数据库字符集改成utf8 utf8_bin

**Comment by AldesFhh** [comment]
我把数据库删了重新开，字符集也改成utf，
也是不行，然后我滚上去看，有个报错是这样的
![image](https://cloud.githubusercontent.com/assets/17841236/26337045/b9c13330-3fa8-11e7-9fa4-102f3c50a228.png)
还有是这样的

![image](https://cloud.githubusercontent.com/assets/17841236/26337057/cc133b1e-3fa8-11e7-92ae-b4deb7218554.png)
然后我npm install express之后就能运行了，可是一直卡在这，我再查查什么问题

![image](https://cloud.githubusercontent.com/assets/17841236/26337092/0a924c7c-3fa9-11e7-8303-9d30764702e2.png)

**Comment by Wizzercn** [comment]
1、npm 安装的node组件js下载不完整；
2、最后一张图，看起来像是启动成功了啊；

**Comment by AldesFhh** [comment]
可是一直卡在那里....waiting就一直waiting

**Comment by AldesFhh** [comment]
可以了可以了，谢谢大神们~~
