### ISSUE TITLE
普通用户访问时，怎么查看文章等内容？

### ISSUE THREAD

**Issue by lx2328** [Wizzercn/NodeWk#8]

**Comment by lx2328** [comment]
前台首页里没有文章等内容啊，要怎么访问呢

**Comment by lx2328** [comment]
![pg9a3784icx34b4okqxck_d](https://user-images.githubusercontent.com/23550512/27209774-711f3056-5280-11e7-8017-9385808beed8.png) 后台里提供的前台首页，跳转之后没有这些栏目，请问具体怎么操作呢？

**Comment by Wizzercn** [comment]
前台需要自己开发啊～～

**Comment by lx2328** [comment]
好吧，我以为这个demo上有呢，谢谢啦~~
